version: '3'
services:
  redis:
    image: "redis:3.0.6"
    ports:
      - "6379:6379"
  rabbitmq-stomp:
    image: "jorgeacetozi/rabbitmq-stomp:3.6"
    ports:
     - "6572:5672"
     - "15672:15672"
     - "61613:61613"
