spring.profiles.active: dev

---

spring:
  profiles: dev
  session:
    store-type: redis  
  messages:
    cache-seconds: 0
  redis:
    host: redis
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

server.session.timeout: 600

bmw:
  chat:
    relay:
      host: rabbitmq-stomp
      port: 61613
